site_name: NULL's Notebook!
site_author: stupid-qzy
#site_url: 'https://notebook.null.top'

repo_url: https://github.com/stupid-qzy/test-mkdocs
repo_name: NULL's Notebook

nav: 
  - 主页:
    - "index.md"
  - 笔记:
    - ZJU:
      # - 微积分(I) | Calculus:
      #   - "notebooks/calculus/8.md"
      #   - "notebooks/calculus/9.md"
      #   - "notebooks/calculus/10.md"
      - 离散数学及其应用 | Discrete Mathematics and Its Applications:
        - "notebooks/dm/1.md"
        - "notebooks/dm/10.md"
        - "notebooks/dm/Glossary.md"
      - 数据结构基础 | Fundamentals of Data Structure:
        - "notebooks/fds/2.md"
        - "notebooks/fds/3.md"
        - "notebooks/fds/4.md"
        - "notebooks/fds/6.md"
        - "notebooks/fds/7.md"
        - "notebooks/fds/8.md"
        - "notebooks/fds/9.md"
      - 数字逻辑设计 | Digital Logic Design:
        - "notebooks/dld/1.md"
        - "notebooks/dld/2.md"
        - "notebooks/dld/3.md"
        - "notebooks/dld/4.md"
        - "notebooks/dld/5.md"
        - "notebooks/dld/6.md"
        - "notebooks/dld/7.md"
        - "notebooks/dld/verilog.md"
    # - Self-Learning:
    #   - CS61A:

    #   - CS61B:
  - 工具: 
    - "tools.md"
  - 经验: 
    - "exp.md"



theme:
  name: material
  
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.annotate

  palette:
    - media: "(prefer-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Light Mode

    - media: "(prefer-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Dark Mode

  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    logo: material/book
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

  custom_dir: overrides

plugins:
  - statistics
  - search
  # - git-revision-date-localized:
  #     type: datetime
  #     timezone: Asia/Shanghai
  #     locale: zh
  #     enable_creation_date: true


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/stupid-qzy

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js


extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - https://unpkg.com/katex@0/dist/katex.min.css
        
copyright: Copyright &copy; 2024 stupid-qzy





