site_name: NoughtQ's Notebook!
site_author: NoughtQ
#site_url: 'https://notebook.null.top'

repo_url: https://github.com/stupid-qzy/notebook
repo_name: NoughtQ's Notebook
use_directory_urls: false

copyright: Copyright &copy; 2024 NoughtQ

nav: 
  - 主页:
    - "index.md"
  - 笔记:
    - 数学相关:
      - 微积分:
        - "notebooks/calculus/7.md"
        - "notebooks/calculus/8.md"
        - "notebooks/calculus/9.md"
        - "notebooks/calculus/10.md"
        - "notebooks/calculus/11.md"
        - "notebooks/calculus/appendix.md" 
      - 离散数学:
        - "notebooks/dm/1.md"
        - "notebooks/dm/2.md"
        - "notebooks/dm/3.md"
        - "notebooks/dm/4.md"
        - "notebooks/dm/5.md"
        - "notebooks/dm/6.md"
        - "notebooks/dm/8.md"
        - "notebooks/dm/9.md"
        - "notebooks/dm/10.md"
        - "notebooks/dm/11.md"
        - "notebooks/dm/Glossary.md"
    - 算法相关:
      - 数据结构基础:
        - "notebooks/fds/2.md"
        - "notebooks/fds/3.md"
        - "notebooks/fds/4.md"
        - "notebooks/fds/5.md"
        - "notebooks/fds/6.md"
        - "notebooks/fds/7.md"
        - "notebooks/fds/8.md"
        - "notebooks/fds/9.md"
    - 硬件相关:
      - 数字逻辑设计:
        - "notebooks/dld/1.md"
        - "notebooks/dld/2.md"
        - "notebooks/dld/3.md"
        - "notebooks/dld/4.md"
        - "notebooks/dld/5.md"
        - "notebooks/dld/6.md"
        - "notebooks/dld/7.md"
        - "notebooks/dld/verilog.md"
    # - Self-Learning:
    #   - CS61A:

    #   - CS61B:
  - 工具: 
    - git: "tools/git.md"
    - vim: "tools/vim.md"

  - 经验: 
    - 面试: "exp/interview.md"
    - 大一の学习经验: "exp/freshman.md"

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate
  font:
    text: JetBrains Mono, LXGW WenKai Screen GB Screen 
    code: JetBrains Mono

  palette:
    - media: "(prefer-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light Mode

    - media: "(prefer-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Dark Mode

  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    logo: material/book
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

  custom_dir: overrides

plugins:
  - statistics: # icon没法正常显示?
      page_template: "stylesheet/template.html"
      words_per_minute: 200
  - search
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      title: 目录

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/stupid-qzy

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  # - javascripts/mathjax.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/extra.css
  - css/counter.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  
  
