site_name: NoughtQ的笔记本
site_author: NoughtQ
site_url: 'https://notebook.noughtq.top'

repo_url: https://github.com/noughtq/notebook
repo_name: NoughtQ/Notebook
use_directory_urls: false

copyright: Copyright &copy; 2024 NoughtQ

nav: 
  - 主页:
    - "index.md"
    - "targets.md"
  - ZJU笔记:
    - 数学相关:
      - 微积分:
        - "notes/ZJU/calculus/index.md"
        - "notes/ZJU/calculus/7.md"
        - "notes/ZJU/calculus/8.md"
        - "notes/ZJU/calculus/9.md"
        - "notes/ZJU/calculus/10.md"
        - "notes/ZJU/calculus/11.md"
        - "notes/ZJU/calculus/appendix.md" 
      - 线性代数:
        - "notes/ZJU/linear-algebra/index.md"
      - 离散数学:
        - "notes/ZJU/dm/index.md"
        - "notes/ZJU/dm/1.md"
        - "notes/ZJU/dm/2.md"
        - "notes/ZJU/dm/3.md"
        - "notes/ZJU/dm/4.md"
        - "notes/ZJU/dm/5.md"
        - "notes/ZJU/dm/6.md"
        - "notes/ZJU/dm/8.md"
        - "notes/ZJU/dm/9.md"
        - "notes/ZJU/dm/10.md"
        - "notes/ZJU/dm/11.md"
        - "notes/ZJU/dm/Glossary.md"
    - 编程语言:
      - C程序设计基础（C小程）:
        - "notes/ZJU/c/index.md"
    - 算法相关:
      - 数据结构基础:
        - "notes/ZJU/fds/index.md"
        - "notes/ZJU/fds/2.md"
        - "notes/ZJU/fds/3.md"
        - "notes/ZJU/fds/4.md"
        - "notes/ZJU/fds/5.md"
        - "notes/ZJU/fds/6.md"
        - "notes/ZJU/fds/7.md"
        - "notes/ZJU/fds/8.md"
        - "notes/ZJU/fds/9.md"
        - Mistakes: "notes/ZJU/fds/mistakes.md"
    - 硬件相关:
      - 数字逻辑设计:
        - "notes/ZJU/dld/index.md"
        - "notes/ZJU/dld/1.md"
        - "notes/ZJU/dld/2.md"
        - "notes/ZJU/dld/3.md"
        - "notes/ZJU/dld/4.md"
        - "notes/ZJU/dld/5.md"
        - "notes/ZJU/dld/6.md"
        - "notes/ZJU/dld/7.md"
        - "notes/ZJU/dld/verilog.md"
      - 杂项:
        - 大学物理:
          - "notes/ZJU/physics/index.md"
     
  - 自学笔记:
    - CS61A:
      - "notes/self-learning/cs61a/index.md"
    - CS61B:
      - "notes/self-learning/cs61b/index.md"
  - 工具: 
    - git: "tools/git.md"
    - vim: "tools/vim.md"

  - 经验: 
    - 专业分流面试: "exp/interview.md"
    - 课程经验分享: 
      - 大一: "exp/freshman.md"

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.prune
    - content.code.copy
    - content.code.annotate
  font:
    text: JetBrains Mono, LXGW WenKai Screen GB Screen 
    code: JetBrains Mono, Consolas, LXGW WenKai Screen GB Screen 

  palette:
    - media: "(prefer-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark Mode

    - media: "(prefer-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light Mode

  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/git-alt
    logo: material/notebook-multiple
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

  custom_dir: overrides

plugins:
  - statistics: # 需要在markdown_extensions里面加一句md_in_html才能显示icon
      page_template: "stylesheet/template.html"
      words_per_minute: 200
  - search
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      fallback_to_build_date: true
  - toc
  - encryptcontent:  
      title_prefix: "🔒 "
      remember_password: True 
      summary: '看不到我~'
      decryption_failure_message: '密码错误'
      encryption_info_message: '应课程政策要求等原因，该文件不对外公开，仅供笔者本人阅读，请见谅！'
      button_class: 'md-search__icon'
      encrypted_something:
        mkdocs-encrypted-toc: [nav, class]


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: ⚓︎
      title: 目录
      toc_depth: 4
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/noughtq

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  # - javascripts/mathjax.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheet/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  
  
